# Домашнее задание к лекции «Продвинутый pandas»

### Задание 1.

Для датафрейма log создать столбец source_type по следующим правилам:

1. Если источник 'traffic_source' равен 'yandex' или 'google', то в 'source_type' ставится 'organic'.
2. Для источников 'paid' и 'email' из России - ставим 'ad'.
3. Для источников 'paid' и 'email' не из России - ставим 'other'.
4. Все остальные варианты берем из 'traffic_source' без изменений.

In [1]:
import pandas as pd

In [37]:
log = pd.read_csv('visit_log.csv', sep=';')

log.loc[log.traffic_source.isin(['yandex', 'google']), 'source_type'] = 'organic'

log.loc[log.traffic_source.isin(['paid', 'email']) & log.region.isin(['Russia']), 'source_type'] = 'ad'

log.loc[log.traffic_source.isin(['paid', 'email']) & ~log.region.isin(['Russia']), 'source_type'] = 'other'

log.loc[log.source_type.isnull(), 'source_type'] = log['traffic_source']

In [38]:
log.head(30)

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,organic
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,organic
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,organic
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,organic
5,1549980742,8855508aad,https://host.ru/df646c3676cc259fa0,Russia,fc43898e47,yandex,organic
6,1549980742,b0f66adc83,https://host.ru/b8b58337d272ee7b15,Russia,13fc55e781,paid,ad
7,1549980754,837885c8f8,https://host.ru/108ce4b365afb7b88e,Russia,cb5082b6f6,direct,direct
8,1549980760,af5570f5a1,https://host.ru/3004a8273caeef2867,China,45664f7af2,direct,direct
9,1549980765,3e7077fd2f,https://host.ru/df646c3676cc259fa0,Russia,6f9de8c8b6,email,ad
10,1549980777,01d448afd9,https://host.ru/a5dda93e70318570c0,India,27e76a4a80,direct,direct
11,1549980785,71b6c1d538,https://host.ru/c8d9213a31839f9a3a,Ukraine,3b13701488,google,organic
12,1549980789,15ec7bf0b5,https://host.ru/8e88d4703848cc0ec4,Russia,6d1d81f7f8,paid,ad
13,1549980792,dd46c3eebb,https://host.ru/3004a8273caeef2867,China,7e301c8c41,direct,direct
14,1549980793,e7ecebbc59,https://host.ru/05e41944dd85a900a6,Belarus,ac52dedc3b,direct,direct
15,1549980797,5322fecfc9,https://host.ru/4adc8a29b212051b04,Belarus,9a45d98867,paid,other
16,1549980801,374708fff7,https://host.ru/39fa884393666d45fc,Russia,e9bd59e22d,google,organic
17,1549980807,0a88111852,https://host.ru/2fcb223266880ccf57,Ukraine,a2ba8fa3db,paid,other
18,1549980814,60daa3a5f7,https://host.ru/ef57543002ce2a0f2a,Belarus,72cb10fb5c,direct,direct
19,1549980816,d6fd62f5ce,https://host.ru/f1eb4601740d627ab0,Belarus,7269dcd869,direct,direct
20,1549980816,de47c9b27e,https://host.ru/8fe7c39e5c598bbc54,Ukraine,2f25b6e26a,email,other
21,1549980823,c90232586b,https://host.ru/da83c74e35e7806fe0,Ukraine,a00405d70c,google,organic
22,1549980827,6a4875ddac,https://host.ru/f2297425e1328e9e35,Ukraine,ea1bf97284,yandex,organic
23,1549980839,015275e61f,https://host.ru/c8d9213a31839f9a3a,Russia,21bdc57777,email,ad
24,1549980842,9d908ecfb6,https://host.ru/ae8a036d7f44d0bcd9,China,583b1a1636,direct,direct
25,1549980844,61126de1b7,https://host.ru/060d9bdbcba66b8bb3,Russia,9de3f97d4f,direct,direct
26,1549980852,659d36ca56,https://host.ru/4adc8a29b212051b04,Russia,c4bd1ae3af,paid,ad
27,1549980853,ea49aa9f6f,https://host.ru/1afc5618562365020a,Russia,20e8e91ecf,email,ad
28,1549980862,3addfb141c,https://host.ru/186c4d6b47dbde0e74,Russia,3f64fc1a87,yandex,organic
29,1549980874,11e431c215,https://host.ru/05e41944dd85a900a6,Russia,a15f66b89b,paid,ad

### Задание 2.
В файле URLs.txt содержатся url страниц новостного сайта. Необходимо отфильтровать его по адресам страниц с текстами новостей. Известно, что шаблон страницы новостей имеет внутри url следующую конструкцию: /, затем 8 цифр, затем дефис. Выполнить следующие действия:

1. Прочитать содержимое файла с датафрейм.
2. Отфильтровать страницы с текстом новостей, используя метод 'str.contains' и регулярное выражение в соответствии с заданным шаблоном.

In [9]:
import re

In [10]:
urls = pd.read_csv('URLs.txt')
urls[urls.url.str.contains('/[0-9]{8}-', regex=True)].head()

                                                 url
3  /politics/36188461-s-marta-zhizn-rossiyan-susc...
4  /world/36007585-tramp-pridumal-kak-reshit-ukra...
5  /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
6  /video/36001498-poyavilis-pervye-podrobnosti-g...
7  /world/36007585-tramp-pridumal-kak-reshit-ukra...

### Задание 3.
Использовать файл с оценками фильмов 'ml-latest-small/ratings.csv'.
Посчитать среднее время жизни пользователей, которые выставили более 100 оценок. Под временем жизни понимается разница между максимальным и минимальным значением столбца 'timestamp' для данного значения 'userId'.

In [55]:
ratings = pd.read_csv('ml-latest-small/ratings.csv', sep=',')

In [56]:
ratings_count = ratings.groupby('userId').count().reset_index()
ratings_count = ratings_count[['userId', 'rating']] # Берем только нужные столбцы.

age_count = ratings_count[ratings_count['rating'] > 100]
# убираем предупреждение SettingWithCopyWarning.
pd.options.mode.chained_assignment = None
age_count.rename(columns={'rating': 'rating_count'}, inplace=True)

In [58]:
ratings_max = ratings.groupby('userId').max().reset_index()
ratings_min = ratings.groupby('userId').min().reset_index()
# берем только нужные столбцы. 
ratings_max = ratings_max[['userId', 'timestamp']]
ratings_min = ratings_min[['userId', 'timestamp']]
# меняем название нужного стольбца в df с max и min значениями.
ratings_max.rename(columns={'timestamp': 'timestamp_max'}, inplace=True)
ratings_min.rename(columns={'timestamp': 'timestamp_min'}, inplace=True)

In [76]:
# объединяем все значения в общую таблицу.
average_timestamp = age_count.merge(ratings_max, how='inner').merge(ratings_min, how='inner')

In [77]:
def average(row):
    ''' Возвращает разницу между максимальным и минимальным значениями "timestamp". 
    '''
    difference = row['timestamp_max'] - row['timestamp_min']
    return difference

In [78]:
average_timestamp['average'] = average_timestamp.apply(average, axis=1)
average_timestamp.head()

   userId  rating_count  timestamp_max  timestamp_min    average
0       4           204      949982274      949778714     203560
1       8           116     1154474527     1154389340      85187
2      15          1700     1469330735      997937239  471393496
3      17           363     1127476640     1127468587       8053
4      19           423      855195373      855190091       5282

### Задание 4.
Дана статистика услуг перевозок клиентов компании по типам. Необходимо сформировать две таблицы:
 1. Таблицу с тремя типами выручки для каждого client_id без указания адреса клиента.
 2. Аналогичную таблицу по типам выручки с указанием адреса клиента.

В процессе объединения таблиц данные не должны теряться.

In [150]:
# железнодорожные перевозки.
rzd = pd.DataFrame(
    {
        'client_id': [111, 112, 113, 114, 115],
        'rzd_revenue': [1093, 2810, 10283, 5774, 981]
    }
)

In [151]:
# автомобильные перевозки.
auto = pd.DataFrame(
    {
        'client_id': [113, 114, 115, 116, 117],
        'auto_revenue': [57483, 83, 912, 4834, 98]
    }
)

In [152]:
# воздушные перевозки.
air = pd.DataFrame(
    {
        'client_id': [115, 116, 117, 118],
        'air_revenue': [81, 4, 13, 173]
    }
)

In [153]:
# адреса клиентов.
client_base = pd.DataFrame(
    {
        'client_id': [111, 112, 113, 114, 115, 116, 117, 118],
        'address': ['Комсомольская 4', 'Энтузиастов 8а', 'Левобережная 1а', 'Мира 14', 'ЗЖБИиДК 1', 
                    'Строителей 18', 'Панфиловская 33', 'Мастеркова 4']
    }
)

In [178]:
# объединяем таблицы с помощью условия 'outer', для сохранения всех строк. 
revenue_table = rzd.merge(auto, how='outer', on='client_id').merge(air, how='outer', on='client_id')

# меняем значения NaN на 0 с помощью фильтра 'isnull'.
revenue_table.loc[revenue_table.rzd_revenue.isnull(), 'rzd_revenue'] = 0
revenue_table.loc[revenue_table.auto_revenue.isnull(), 'auto_revenue'] = 0
revenue_table.loc[revenue_table.air_revenue.isnull(), 'air_revenue'] = 0

revenue_table

   client_id  rzd_revenue  auto_revenue  air_revenue
0        111       1093.0           0.0          0.0
1        112       2810.0           0.0          0.0
2        113      10283.0       57483.0          0.0
3        114       5774.0          83.0          0.0
4        115        981.0         912.0         81.0
5        116          0.0        4834.0          4.0
6        117          0.0          98.0         13.0
7        118          0.0           0.0        173.0

In [174]:
# Аналогичная таблица, но с добавленными адресами клиентов из df 'client_base'.
revenue_table_with_address = revenue_table.merge(client_base, how='outer', on='client_id')
revenue_table_with_address

   client_id  rzd_revenue  auto_revenue  air_revenue          address
0        111       1093.0           0.0          0.0  Комсомольская 4
1        112       2810.0           0.0          0.0   Энтузиастов 8а
2        113      10283.0       57483.0          0.0  Левобережная 1а
3        114       5774.0          83.0          0.0          Мира 14
4        115        981.0         912.0         81.0        ЗЖБИиДК 1
5        116          0.0        4834.0          4.0    Строителей 18
6        117          0.0          98.0         13.0  Панфиловская 33
7        118          0.0           0.0        173.0     Мастеркова 4